server:
  port: 8992


spring:
  application:
    name: gateway
  cloud:
    nacos:  #指定nacos注册中心地址
      server-addr: 192.168.108.149:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
    gateway:
      routes:

        - id: user_route
          uri:   http://localhost:9003/     #lb://yingxue_user  #
          predicates:
            - Path=/admin/users/**

        - id: video_route			  # 指定路由唯一标识
          uri: http://localhost:9002/ # 指定路由服务的地址  lb://users
          predicates:
            - Path=/admin/videos/**			 # 指定路由规则
        - id: category_route			 # 指定路由唯一标识
          uri: http://localhost:9001/ # 指定路由服务的地址  lb://users
          predicates:
            - Path=/admin/categories/**			 # 指定路由规则
      globalcors:   #配置跨域
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
        add-to-simple-url-handler-mapping: true
